### ISSUE TITLE
How to add: "Gratis"

### ISSUE THREAD

**Issue by mrNathanNFT** [jensjeflensje/marktplaats-py#6]
Hello, 

I want it so the scraper only filters for "Gratis" in price, but that doesn't work. How can I fix it? 

I tried this: 

`
 price_from="Gratis", # Lowest price to search for
 `
 `
 price_to="Gratis", # Highest price to search for
`

**Comment by jensjeflensje** [comment]
I just realized there is no example for sorting. So I'll show you one here. I'll add it to the readme as well :)
```py
from marktplaats import SearchQuery, SortBy

search = SearchQuery("fiets", sort_by=SortBy.PRICE)
```

**Comment by mrNathanNFT** [comment]
Hi Jens! Thanks for your help! 

What I am trying to build is a code that gives me a notification every time someone within 10km of my reach posts a "Gratis" advertisement on marktplaats.nl. Can you help me with that? Because when I try to filter with 0, 0 is only gives me the advertisements of people that are selling it for 0,00. But there is also an option for the seller to make it: "Gratis". 

Thanks in advance! 

Nathan :)

**Comment by jensjeflensje** [comment]
As I've said and shown in my example, sorting by price should work. Loop through that list of items, and stop the loop when you encounter ads above a price of 0. That'll give you all the free ads.

**Comment by mrNathanNFT** [comment]
Thanks, and is there also a way to not filter for words in title? I mean so I get all the items that are free?

**Comment by jensjeflensje** [comment]
You could try to just put in an empty string, but I'm not sure if that'll work without any other filters.
You could also try to add generic Dutch words that get used in most sentences, like 'het' or 'de'. They'll match any ad 🙈

**Comment by jensjeflensje** [comment]
I added you

**Comment by mrNathanNFT** [comment]
Great! Added you back!
